### ISSUE TITLE
Incorrect variable principle

### ISSUE THREAD

**Issue by pragmaticAweds** [CloudCoded/30-Days-Of-JavaScript#12]
What's the first golden principle that you are missing here?

![Screenshot_2023-05-07-11-49-44-861_com android chrome-edit](https://user-images.githubusercontent.com/70960505/236673106-014a31c5-9bf7-4afb-81e5-47fc22c6303c.jpg)

**Comment by CloudCoded** [comment]
Golden principle? There's no golden principle, I'm using the first declarations

**Comment by pragmaticAweds** [comment]
What if you reassign a new value to the ones you've used without you remembering

**Comment by CloudCoded** [comment]
Correct done sir.

**Comment by pragmaticAweds** [comment]
👍
