### ISSUE TITLE
Where's your country at

### ISSUE THREAD

**Issue by pragmaticAweds** [CloudCoded/30-Days-Of-JavaScript#3]
The country data you are using, where did you store it to?

You wanted to create a copy of country and still assigning it to the same variable > countries.slice(countries, countries.length)

Not acceptable

Using const doesn't affect push method, replace let with const

**Comment by CloudCoded** [comment]
Could you please be specific sir. I used the array countries in many places so I'm confused sir

**Comment by CloudCoded** [comment]
and how about the push method, are you refering to an exercise i solve in day 6?

**Comment by pragmaticAweds** [comment]
Day 6 exercise 3, I didn't see where the countries array you are using to solve the problem, also check line 34 of exercise 3 day 6.

Also the last question where you are told to reverse, you shouldn't create a new array, but the same array you have been using, instead you can create a copy and use it to solve the solution.

**Comment by CloudCoded** [comment]
All issue resolved sir. 

countries, webTechs, mernStack arrays stored in main.js

and I assigned a new var to the copy country 

and  I changed the let to const

and the last question sir, I did the correction. I created a copy and use it to solve the solution.
ALL ISSUES RESOLVED SIR.

**Comment by pragmaticAweds** [comment]
Good
